drop TABLE  if exists ROLE;

CREATE TABLE ROLE(
	ROLE_ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '角色编号',
	ROLE_NAME VARCHAR(30) NOT NULL COMMENT '角色名称',
	ROLE_DESCRIPTION VARCHAR(200) COMMENT '角色描述',
	ROLE_ICON VARCHAR(200) NOT NULL COMMENT '角色图标',
	ROLE_CREATED_DATETIME VARCHAR(50) NOT NULL COMMENT '创建时间',
	ROLE_CREATED_USERID INT(11) NOT NULL COMMENT '创建人名',
	ROLE_UPDATED_DATETIME VARCHAR(50) NOT NULL COMMENT '修改时间',
	ROLE_UPDATED_USERID INT(11) NOT NULL COMMENT '修改人名'
	)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;